- name: Install MySQL database
  yum:
    name: mysql-community-server
    state: present

- name: Start MySQL service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Create database
  mysql_db: 
    name: '{{ db_name }}' 
    state: present

- name: Create database users
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_user_password }}'
    priv: '*.*:ALL'
    state: present